disabled_rules:
  - opening_brace # not compatible to SwiftFormat rule "wrapMultilineStatementBraces"
excluded:
  - .build
file_length:
  warning: 500
  ignore_comment_only_lines: true
force_cast: error
force_try: error
function_body_length: 80
function_parameter_count: 7
identifier_name:
  excluded:
    - id
line_length:
  warning: 160
  ignores_comments: true
  ignores_interpolated_strings: true
nesting:
  type_level: 2
opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - operator_usage_whitespace
  - overridden_super_call
type_body_length: 300
