disabled_rules:
  - force_try
  - force_unwrapping
  - identifier_name
  - implicitly_unwrapped_optional
  - inclusive_language
  - multiple_closures_with_trailing_closure
  - type_body_length
  - type_contents_order
  - type_name
excluded:
  - .build
file_length: 1400
line_length: 200
opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_cast
  - multiline_arguments
  - operator_usage_whitespace
  - overridden_super_call
